### ISSUE TITLE
Unnecessary database queries on credits page

### ISSUE THREAD

**Issue by swissspidy** [stuttter/wp-user-avatars#11]
WP User Avatars filters `get_avatar_url` to see if the email belongs to a WordPress user and if that user has a custom avatar.

On `wp-admin/credits.php`, this results in about 100 unnecessary database queries like this:

```sql
SELECT *
FROM wp_users
WHERE user_email = 'xyz@md5.gravatar.com'
```

To prevent this, I suggest skipping avatar retrieval for `@md5.gravatar.com` email addresses.

Right now I'd need to manually unhook `wp_user_avatars_filter_get_avatar_url()` for such cases, but a fix in the plugin makes more sense to me.

**Comment by JJJ** [comment]
Fixed in 1.2.0.
