### ISSUE TITLE
Add filter to get_avatar_url or get_avatar_data instead get_avatar, or provide function get_user_avatar_data

### ISSUE THREAD

**Issue by marsjaninzmarsa** [stuttter/wp-user-avatars#2]
I need an URL to avatar image, not `<img>` tag - with your plugin I must scrap provided tag with regex or duplicate lot of your code to get this data.

**Comment by swissspidy** [comment]
Yep, such a filter would be awesome!

**Comment by johnjamesjacoby** [comment]
This will happen for sure in a future release. These functions were just being put in when this code was being written originally, so I'll double back and update it to use these.

Pull requests welcome, too!

**Comment by johnjamesjacoby** [comment]
Haven't forgotten about this, I just haven't needed to prioritize it.

**Comment by slaFFik** [comment]
@johnjamesjacoby Will you be able to work of this any time soon?

**Comment by JJJ** [comment]
> Will you be able to work on this any time soon?

Clearly, I wasn't. But I will try to.

**Comment by JJJ** [comment]
Done for 1.0.0!
