### ISSUE TITLE
 WebP Support

### ISSUE THREAD

**Issue by misfist** [stuttter/wp-user-avatars#28]
Hi there!

Thanks for the great plugin!

Since 5.8, WP has WebP support, but WP User Avatarss uploader doesn’t seem to support it. When attempting to upload a WebP image from the User Profile edit page, there is an error: “Avatar upload failed”. Adding a WebP image from the Media Library does work, however.

I assume this because WebP isn’t set as one of the accepted image formats:

```
// Handle upload
$avatar = wp_handle_upload( $_FILES['wp-user-avatars'], array(
    'mimes' => array(
        'jpg|jpeg|jpe' => 'image/jpeg',
        'gif'          => 'image/gif',
        'png'          => 'image/png',
    ),
    'test_form' => false,
    'unique_filename_callback' => 'wp_user_avatars_unique_filename_callback'
) );

```

https://github.com/stuttter/wp-user-avatars/blob/master/wp-user-avatars/includes/common.php#L56-L64

Would it be possible to allow WebP images in the upload?

ref: https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/

Note: This is duplicated on the WP support forum here: https://wordpress.org/support/topic/webp-support-35/

**Comment by JJJ** [comment]
Merged! Thanks @misfist!
