### ISSUE TITLE
Styling issue on profile page in wp-admin

### ISSUE THREAD

**Issue by slaFFik** [stuttter/wp-user-avatars#5]
See screenshot

![image](https://cloud.githubusercontent.com/assets/282234/15323490/ffcb8772-1c4a-11e6-86d7-9085bd5008c5.png)

WordPress 4.5, BuddyPress 2.5

**Comment by JJJ** [comment]
I *think* I fixed this. If not, it should be easy enough.

**Comment by JJJ** [comment]
Not fixed.

See: https://buddypress.trac.wordpress.org/ticket/7353
