### ISSUE TITLE
Unable to keep custom class set to image when activated

### ISSUE THREAD

**Issue by leecollings** [stuttter/wp-user-avatars#7]
Previously, I was able to set a class and other parameters tot he image tag when using default Wordpress avatars using this:

```
get_avatar($user->ID, 150, null, get_the_author(array('class'=>'img-responsive img-circle center-block'))
```

But now, when this plugin is activated, it doesn't take this standard function, and my classes disappear. How can I get the above call to work with your plugin and apply the class, and size?

**Comment by JJJ** [comment]
Since 1.0.0, this plugin now uses `get_avatar()` and your custom classes should all stay intact.

Thanks @leecollings for reporting this.
